[book]
authors = ["Cédric Eyssette"]
language = "fr"
multilingual = false
src = "src"
title = "Section euro Anglais (2021-2022) : DNL"
description = "Cours de DNL Philosophie / Anglais de M. Eyssette (2021-2022)"

[build]
build-dir = "c"

[output.html]
no-section-label = true
additional-css = ["custom.css"]
additional-js = ["custom.js"]

[output.html.fold]
enable = true
level = 1