[book]
authors = ["Cédric Eyssette"]
language = "fr"
multilingual = false
src = "src"
title = "Cours de philosophie (2021-2022) : séries générales"
description = "Cours de philosophie de M. Eyssette (2021-2022) : séries générales"

[build]
build-dir = "c"

[output.html]
no-section-label = true
additional-css = ["custom.css", "sidebar-toc.css"]
additional-js = ["custom.js", "sidebar-toc.js"]

[output.html.fold]
enable = true
level = 1